### ISSUE TITLE
Intersection Issue

### ISSUE THREAD

**Issue by benoitxp** [GouMinghao/Geometry3D#1] opened 2021-08-02 14:09 UTC
Hi,

Really enjoy this library but I have a small problem and I can't figure out why it isn't working.
I want to calculate the intersection between two planes, but some calculations return a None even if the planes doe have an intersection?
Does someone have any ideas?

This is my code:

`from Geometry3D import *

plane1 = ConvexPolygon((Point(61.32, 0.0, 0.58), Point(-0.21, 50.58, -28.91), Point(-0.21, 0.0, -28.91)))
plane2 = ConvexPolygon((Point(-50.21, 20.0, -78.91), Point(-50.21, 20.0, 50.58), Point(111.32, 20.0, 50.58), Point(111.32, 20.0, -78.91)))

inter = intersection(plane1,plane2)
print(inter)

r = Renderer()
r.add((plane1,'r',2))
r.add((plane2,'b',2),normal_length = 0)
r.show()`

**Comment by GouMinghao** [comment] 2021-08-03 12:44
Thanks for you bug report, it seems that it is indeed a bug.
I will try to fix it as soon as possible!

**Comment by GouMinghao** [comment] 2021-08-04 03:16
Thank you again for you report, this bug is caused by numerical inaccuracy and has been addressed in https://github.com/GouMinghao/Geometry3D/pull/2. If you have any other question you can ask me later.

**Comment by GouMinghao** [comment] 2021-08-05 07:57
issue closed as there is no further discussion

**Comment by benoitxp** [comment] 2021-08-06 13:37
Hey,

Thank you for solving the bug so quickly 🙌.

I have another question related to this issue:
`
plane1 = ConvexPolygon((Point(171.76, 98.39, -36.5), Point(0.0, 0.0, -0.0), Point(171.76, 0.0, -0.0)))
plane2 = ConvexPolygon((Point(-50.0, 10.0, -86.5), Point(-50.0, 10.0, 50.0), Point(221.76, 10.0, 50.0), Point(221.76, 10.0, -86.5)))
`

It looks like these coordinates give me a similar error.
Even tho there is also an intersection.

Any thoughts?

Thanks in advance

**Comment by GouMinghao** [comment] 2021-08-07 05:15
Thank you for another bug report, it is caused by the bug or my misunderstanding in the solver module provided by the old repo [sgl](https://github.com/Kingdread/sgl). Instead, I reimplement a method to solve this problem. 
The bug has be addressed in https://github.com/GouMinghao/Geometry3D/pull/4.

**Comment by benoitxp** [comment] 2021-08-07 17:38
Awesome work!
Just tested it and it works perfect!

PS: Is it possible that the update isn't yet installable with pip?

**Comment by GouMinghao** [comment] 2021-08-08 04:20
It should be able to be installed using pip as I have uploaded the latest version to pypi. Maybe you have installed the old`` version. To update it using 'pip install Geometry3D'

**Comment by benoitxp** [comment] 2021-09-29 12:59
Hey,

I think I found another case related to this issue.
These are my coordinates:

`plane1 = ConvexPolygon((Point(156.05, 0.0, -1189.0), Point(156.05, 1000.0, -122.42), Point(156.05, 0.0, -122.42)))
plane2 = ConvexPolygon((Point(106.05000000000001, 330.0, -1239.0), Point(106.05000000000001, 330.0, -72.42), Point(206.05, 330.0, -72.42), Point(206.05, 330.0, -1239.0)))`

The answer I get when doing an intersection is only one point ( answer: Point(156.05, 330.0, -122.42000000000007) ). But I by making a visualization then their is another point missing:
![Screenshot 2021-09-29 at 14 56 44](https://user-images.githubusercontent.com/44461240/135272766-c7451e6f-261e-4703-8b45-7409f290e3c1.png)

Thanks in advance,
You're awesome!

**Comment by GouMinghao** [comment] 2021-12-04 15:24
So sorry for the very long time delay as I'm busy finding a job these days.
This problem is caused by the inaccuracy of the vector calculation.
It is solved in this commit https://github.com/GouMinghao/Geometry3D/commit/99d97ef302754d6b98a2fcb8f910602fa97fc49f

**Comment by benoitxp** [comment] 2021-12-07 10:12
Hi,

Thank you. I will try to test it as soon as possible.

Thanks

**Comment by benoitxp** [comment] 2021-12-10 16:35
Hi,

I've found another small problem

Input:
```
ConvexPolygon((Point(1350.16, 665.0, 2095.33), Point(1350.16, 0.0, 1487.0), Point(1350.16, 665.0, 1487.0)))
ConvexPolygon((Point(1300.16, 200.0, 1437.0), Point(1300.16, 200.0, 2145.33), Point(1400.16, 200.0, 2145.33), Point(1400.16, 200.0, 1437.0)))
```

Output:
`Point(1350.16, 200.0, 1487.0)`

**Comment by ldo** [comment] 2022-02-02 04:56
Why not use [`math.isclose()`](https://docs.python.org/3/library/math.html#math.isclose) to do the approximately-equal comparison? Just to save some effort.

**Comment by GouMinghao** [comment] 2022-04-05 08:44
> Why not use [`math.isclose()`](https://docs.python.org/3/library/math.html#math.isclose) to do the approximately-equal comparison? Just to save some effort.

Thank you for your suggestion. However, this library relays heavily on precise floating point calculation. Using `math.isclose` is not easy to manage the precision.

**Comment by GouMinghao** [comment] 2022-04-05 08:46
> Hi,
> 
> I've found another small problem
> 
> Input:
> 
> ```
> ConvexPolygon((Point(1350.16, 665.0, 2095.33), Point(1350.16, 0.0, 1487.0), Point(1350.16, 665.0, 1487.0)))
> ConvexPolygon((Point(1300.16, 200.0, 1437.0), Point(1300.16, 200.0, 2145.33), Point(1400.16, 200.0, 2145.33), Point(1400.16, 200.0, 1437.0)))
> ```
> 
> Output: `Point(1350.16, 200.0, 1487.0)`

It has been a long time since this bug report, but it seems to be solved in [here](https://github.com/GouMinghao/Geometry3D/blob/0.3.0/g3d_tests/test9.py).

New patch will come soon.

**Closed** 2022-04-05 08:48 UTC
